export const images = [
  {
    image:
      'https://raw.githubusercontent.com/ShreyasDamase/NomadTravelerImages/refs/heads/main/BackGround/1.jpg',
  },
  {
    image:
      'https://raw.githubusercontent.com/ShreyasDamase/NomadTravelerImages/refs/heads/main/BackGround/2.jpg',
  },
  {
    image:
      'https://raw.githubusercontent.com/ShreyasDamase/NomadTravelerImages/refs/heads/main/BackGround/3.jpg',
  },
  {
    image:
      'https://raw.githubusercontent.com/ShreyasDamase/NomadTravelerImages/refs/heads/main/BackGround/4.jpg',
  },
  {
    image:
      'https://raw.githubusercontent.com/ShreyasDamase/NomadTravelerImages/refs/heads/main/BackGround/5.jpg',
  },
  {
    image:
      'https://raw.githubusercontent.com/ShreyasDamase/NomadTravelerImages/refs/heads/main/BackGround/6.jpg',
  },
  {
    image:
      'https://raw.githubusercontent.com/ShreyasDamase/NomadTravelerImages/refs/heads/main/BackGround/7.jpg',
  },
  {
    image:
      'https://raw.githubusercontent.com/ShreyasDamase/NomadTravelerImages/refs/heads/main/BackGround/8.jpg',
  },
  {
    image:
      'https://raw.githubusercontent.com/ShreyasDamase/NomadTravelerImages/refs/heads/main/BackGround/9.jpg',
  },
  {
    image:
      'https://raw.githubusercontent.com/ShreyasDamase/NomadTravelerImages/refs/heads/main/BackGround/10.jpg',
  },
  {
    image:
      'https://raw.githubusercontent.com/ShreyasDamase/NomadTravelerImages/refs/heads/main/BackGround/11.jpg',
  },

  {
    image:
      'https://raw.githubusercontent.com/ShreyasDamase/NomadTravelerImages/refs/heads/main/BackGround/12.jpg',
  },

  {
    image:
      'https://raw.githubusercontent.com/ShreyasDamase/NomadTravelerImages/refs/heads/main/BackGround/13.jpg',
  },

  {
    image:
      'https://raw.githubusercontent.com/ShreyasDamase/NomadTravelerImages/refs/heads/main/BackGround/14.jpg',
  },

  {
    image:
      'https://raw.githubusercontent.com/ShreyasDamase/NomadTravelerImages/refs/heads/main/BackGround/15.jpg',
  },

  {
    image:
      'https://raw.githubusercontent.com/ShreyasDamase/NomadTravelerImages/refs/heads/main/BackGround/16.jpg',
  },

  {
    image:
      'https://raw.githubusercontent.com/ShreyasDamase/NomadTravelerImages/refs/heads/main/BackGround/17.jpg',
  },
  {
    image:
      'https://raw.githubusercontent.com/ShreyasDamase/NomadTravelerImages/refs/heads/main/BackGround/18.jpg',
  },
];
